apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-nginx-d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-nginx-d
    spec:
      containers:
      - name: hello-nginx-d
        image: nginx
        ports:
        - containerPort: 80